### ISSUE TITLE
Trying to install but fails

### ISSUE THREAD

**Issue by 4integration** [BESTSELLER/backstage-plugin-harbor#57]
Hi,

I have followed the instructions.
However I didn't have `packages/app/src/plugins.ts` file but created it with the content.
When starting backstage `yarn dev` I get an error which I relates to this plugin
```
[0] ERROR in ../../node_modules/react-data-table-component/dist/index.cjs.js 1:102-130
[0] Module not found: Error: Can't resolve 'styled-components' in '/home/my-uid/projects/devexp/playbook-backstage/backstage-site/node_modules/react-data-table-component/dist'
[0]
[0] webpack compiled with 1 error
```

**Comment by briandesousa** [comment]
I ran into this same error. It looks like one of this plugin's dependencies, [react-data-table-component](https://github.com/jbetancur/react-data-table-component/tree/v6.11.8), requires the styled-components package to be installed, but doesn't include it in its package.json.

After installing the latest version of styled-components to the `packages/app` directory of your Backstage installation, you should be able to get further.

**Comment by 4integration** [comment]
Thanks @briandesousa that made it running but not working.
Do you know if this plugin works with Harbor v2.x (which we use)?

We have v2.x and I see `${backendUrl}/api/harbor/artifacts?project=${props.project}&repository=${props.repository}` in the code but in Harbor API docs it says baseUrl `harbor.company.net/api/v2.0` and endpoint `/projects/{project_name}/repositories/{repository_name}/artifacts`

Getting:
```
Error
TypeError

Message
Cannot read properties of undefined (reading 'repoUrl')

Stack Trace
TypeError: Cannot read properties of undefined (reading 'repoUrl')
    at HarborRepository (webpack-internal:///../../node_modules/@bestsellerit/backstage-plugin-harbor/dist/index.esm.js:247:25)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:18)
    at updateFunctionComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17035:20)
    at beginWork (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18611:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293:31)
    at beginWork$1 (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23204:7)
    at performUnitOfWork (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22158:12)
    at workLoopSync (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22131:22)
```

**Comment by briandesousa** [comment]
You are now stuck at the same error that I am stuck at. I wasn't quite sure if it was something that I was doing wrong but I am seeing the exact same error. I did a little bit of digging into the plugin's source code but I wasn't able to figure out exactly why this failure is occurring. It seems that the [call to the Harbor V2 API from backstage-plugin-harbor-backend](https://github.com/BESTSELLER/backstage-plugin-harbor-backend/blob/master/src/service/artifact.ts#L36-L58) is failing silently ultimately resulting 404 not found returned from the Backstage backend. I couldn't find any logs to indicate why it was failing though...

**Comment by 4integration** [comment]
@briandesousa I thing I found the issue.
It seems that cannot handle images with multi `/`. Typically we have multi-slashes like `<project>/<team>/<image>` but tested with a `<project>/<image>` (something we replicate) and that works.
Will register another issue in backend project

**Comment by 4integration** [comment]
https://github.com/BESTSELLER/backstage-plugin-harbor-backend/issues/5

**Comment by wrighbr** [comment]
Hi @4integration and @briandesousa 
I noticed that sometimes the backend is slow to response so I increase the timeout https://github.com/BESTSELLER/backstage-plugin-harbor/commit/4f2c0ec15fbe402ce6a1f2da1008363a9f23c492
this should fix the problem

**Comment by briandesousa** [comment]
Unfortunately, the timeout increase didn't seem to help. The harbor backend plugin is responding but with a 404 not found:

![image](https://user-images.githubusercontent.com/5022414/136497269-617bb3f2-8b1d-4486-8d79-a9ee55213abc.png)

Its entirely possible I have something misconfigured though...

**Comment by wrighbr** [comment]
@briandesousa do you know what port your backend is running on? 3000 or 7000. Also do you get a response from localhost:7000/api/harbor/health

**Comment by wrighbr** [comment]
@briandesousa I also noticed I was referencing some of the json wrong in the front end I've fixed this and created a new release

**Comment by 4integration** [comment]
Thanks @wrighbr but I still have the multi-level issue and registered some new info in harbor-backend https://github.com/BESTSELLER/backstage-plugin-harbor-backend/issues/5
